/*
 * User Application
 *
 * User Application
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapigen_gin_no_interface

import (
	"github.com/gin-gonic/gin"
)

type UserAPI struct {
}

// Put /api/v1/users/:userId
func (api *UserAPI) ApiV1UsersUserIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/users
// creates a user
func (api *UserAPI) CreateUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/users/:userId
// delete a user
func (api *UserAPI) DeleteUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/users/:userId
// get user
func (api *UserAPI) GetUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
