/*
 * User Application
 *
 * User Application
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/bbakla/openapi3-with-go/api/openapigenonlyinterface"
	openapigen_gin "github.com/bbakla/openapi3-with-go/open-api-gin"
	"log"
	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
)

func main() {
	routes := openapigen_gin.ApiHandleFunctions{UserAPI: openapigenonlyinterface.NewUserAPI()}

	log.Printf("Server started")

	router := openapigen_gin.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
