/*
 * User Application
 *
 * User Application
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapigen_gin

import (
	"time"
)

// User - saved user
type User struct {
	Name string `json:"name,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	Email string `json:"email,omitempty"`

	Id int64 `json:"id"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
