/*
 * User Application
 *
 * User Application
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapigen_gin_interface

import (
	"github.com/gin-gonic/gin"
)

type UserAPI interface {

	// ApiV1UsersUserIdPut Put /api/v1/users/:userId
	ApiV1UsersUserIdPut(c *gin.Context)

	// CreateUser Post /api/v1/users
	// creates a user
	CreateUser(c *gin.Context)

	// DeleteUser Delete /api/v1/users/:userId
	// delete a user
	DeleteUser(c *gin.Context)

	// GetUser Get /api/v1/users/:userId
	// get user
	GetUser(c *gin.Context)
}
